spring:
  application:
    name: student-management-system
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:qlsv_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

# Thymeleaf Configuration
spring.thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:MySecretKeyForStudentManagementSystem2024VeryLongAndSecure}
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    root: INFO
    com.qlsv: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
